---
- name: Template dovecot.conf
  become: true
  ansible.builtin.template:
    src: templates/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    mode: "0644"
  notify: systemctl restart dovecot

- name: Template dovecot-sql.conf
  become: true
  ansible.builtin.template:
    src: templates/dovecot-sql.j2
    dest: /etc/dovecot/dovecot-sql.conf
    mode: "0440"
  notify: systemctl restart dovecot

- name: Copy spam-global.sieve
  become: true
  ansible.builtin.copy:
    src: files/spam-global.sieve
    dest: /var/vmail/sieve/global/spam-global.sieve
    owner: vmail
    group: vmail
    mode: "0644"
  notify:
    - systemctl restart dovecot
    - sievec spam-global.sieve

- name: Copy learn-spam.sieve
  become: true
  ansible.builtin.copy:
    src: files/learn-spam.sieve
    dest: /var/vmail/sieve/global/learn-spam.sieve
    owner: vmail
    group: vmail
    mode: "0644"
  notify:
    - systemctl restart dovecot
    - sievec learn-spam.sieve

- name: Copy learn-ham.sieve
  become: true
  ansible.builtin.copy:
    src: files/learn-ham.sieve
    dest: /var/vmail/sieve/global/learn-ham.sieve
    owner: vmail
    group: vmail
    mode: "0644"
  notify:
    - systemctl restart dovecot
    - sievec learn-ham.sieve
