---
- name: systemctl restart dovecot
  become: true
  ansible.builtin.systemd:
    name: 'dovecot'
    state: 'restarted'

- name: sievec spam-global.sieve
  become: true
  ansible.builtin.command: sievec /var/vmail/sieve/global/spam-global.sieve

- name: sievec learn-spam.sieve
  become: true
  ansible.builtin.command: sievec /var/vmail/sieve/global/learn-spam.sieve

- name: sievec learn-ham.sieve
  become: true
  ansible.builtin.command: sievec /var/vmail/sieve/global/learn-ham.sieve
